services:
  postgres2:
    container_name: ms-pg-sql2
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234567890
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5433:5432
    networks:
      - microservices-net
    restart: unless-stopped

  pgadmin2:
    container_name: ms_pgadmin2
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - microservices-net
    restart: unless-stopped

  mongodb2:
    container_name: ms_mongo_db2
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data

    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234567890

  mongo-express2:
    container_name: ms_mongo_express2
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8083:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1234567890
      ME_CONFIG_MONGODB_SERVER: mongodb
  #      ME_CONFIG_MONGODB_ENABLE_ADMIN: false

  zookeeper3:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper3
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - microservices-net
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: ms_kafka2
    ports:
      - 9092:9092
    depends_on:
      - zookeeper3
    environment:
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeepker2:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
    networks:
      - microservices-net
    restart: unless-stopped


  mail-dev2:
    container_name: ms_mail_dv2
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

#  zipkin:
#    container_name: zipkin
#    image: openzipkin/zipkin
#    ports:
#      - 9411:9411
#    networks:
#      - microservices-net

networks:
  microservices-net:
    name: e-commerce-ap_microservices-net
    driver: bridge

volumes:
  postgres:
  pgadmin:
  mongo:
